services:

#################
# RADARR
#################

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    privileged: true
    group_add:
      - "44"
      - "992"
    volumes:
      - /mnt/user/appdata/radarr:/config
      - /mnt/user/data/media/movies:/movies
      - /mnt/user/data/torrents:/downloads
    restart: unless-stopped

#################
# SONARR
#################

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/user/appdata/sonarr:/config
      - /mnt/user/data/media/tv:/tv
      - /mnt/user/data/torrents:/downloads
    restart: unless-stopped

#################
# PROWLARR
#################

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/user/appdata/prowlarr:/config
    restart: unless-stopped

#################
# QBITTORRENT
#################

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /mnt/user/appdata/qbittorrent:/config
      - /mnt/user/data/torrents:/downloads
    restart: unless-stopped

#################
# JELLYFIN
#################

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "44"
      - "992"
    environment:
      - JELLYFIN_FFmpeg__probesize=50M
      - JELLYFIN_FFmpeg__analyzeduration=50M
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/user/appdata/jellyfin:/config
      - /mnt/user/appdata/jellyfin-cache:/cache
      - /mnt/user/data/media/tv:/data/tvshows
      - /mnt/user/data/media/movies:/data/movies
      - /mnt/user/data/media/anime:/data/anime
      - /mnt/user/appdata/jellyfin-cache/transcodes:/transcodes
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    restart: unless-stopped

#################
# SONARR-ANIME
#################

  sonarr-anime:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-anime
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/user/appdata/sonarr-anime:/config
      - /mnt/user/data/media/anime:/anime
      - /mnt/user/data/torrents:/downloads
    ports:
      - "8990:8989"
    restart: unless-stopped
#################
# GLUETUN
#################
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    dns:
      - 1.1.1.1
      - 8.8.8.8
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "44"
      - "992"
    ports:
      - 7878:7878 #radarr
      - 8989:8989 #sonarr
      - 9696:9696 #prowlarr
      - 8080:8080 #qbittorrent
      - 6881:6881 #qbittorrent
      - 6881:6881/udp #qbittorrent
      - 6868:6868 #profilarr
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES=united states
      - FIREWALL_INPUT_PORTS=${FIREWALL_INPUT_PORTS}
    restart: unless-stopped

#################
# JELLYSEERR
#################

  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    init: true
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/New_York
      - PORT=5055
    ports:
      - 5055:5055
    volumes:
      - /mnt/user/appdata/jellyseerr:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped

#################
# PROFILARR
#################

  profilarr:
    image: santiagosayshey/profilarr:latest
    container_name: profilarr
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    volumes:
      - /mnt/user/appdata/Profilarr:/config
    environment:
      - TZ=UTC
    restart: unless-stopped

#################
# NGINX PROXY MANAGER
#################

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    networks:
      default:
        aliases:
          - npm
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - /mnt/user/appdata/npm:/data
      - npm_letsencrypt:/etc/letsencrypt
    restart: unless-stopped

#################
# ERSATZTV
#################

  ersatztv:
    image: ghcr.io/ersatztv/ersatztv
    container_name: ersatztv
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "44"
      - "992"
    environment:
      - TZ=America/New_York
# UNCOMMENT THESE LINES TO ENABLE NVIDIA GPU PASSTHROUGH
      #- NVIDIA_VISIBLE_DEVICES=all
      #- NVIDIA_DRIVER_CAPABILITIES=all
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: 1
    #          capabilities: [gpu]
    ports:
      - "8409:8409"
    volumes:
      - /mnt/user/appdata/ersatztv:/config
      - /mnt/user/data/media/movies:/data/movies:rw
      - /mnt/user/data/media/tv:/data/tv:rw
      - /mnt/user/data/media/anime:/data/anime:rw
    tmpfs:
      - /transcode
    restart: unless-stopped

#################
# HOMARR
#################

  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    environment:
      - SECRET_ENCRYPTION_KEY=${HOMARR_SECRET_KEY}
    ports:
      - "7575:7575"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/user/appdata/homarr:/appdata
    restart: unless-stopped

#################
# BAZARR
#################

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/user/appdata/bazarr:/config
      - /mnt/user/data/media/movies:/movies #optional
      - /mnt/user/data/media/tv:/tv #optional
      - /mnt/user/data/media/anime:/data/anime
    ports:
      - 6767:6767
    restart: unless-stopped

#################
# CLOUDFLARED
#################

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run kaijuvault
    volumes:
      - /mnt/user/appdata/cloudflared:/etc/cloudflared
    restart: unless-stopped

#################
# UPTIME KUMA
#################

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - /mnt/user/appdata/uptime-kuma:/app/data
    ports:
      - "3001:3001"
    restart: unless-stopped

#################
# PORTAINER
#################

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/user/appdata/portainer:/data
    restart: unless-stopped

volumes:
  npm_letsencrypt:
