tunnel: TUNNEL_ID_PLACEHOLDER
credentials-file: /etc/cloudflared/TUNNEL_ID_PLACEHOLDER.json

ingress:
  - hostname: jf.kaijuvault.net
    service: http://npm:80
  - hostname: klipper.kaijuvault.net
    service: http://npm:80
  - hostname: mealie.kaijuvault.net
    service: http://npm:80
  - hostname: nginx.kaijuvault.net
    service: http://npm:80
  - hostname: portainer.kaijuvault.net
    service: http://npm:80
  - hostname: profilarr.kaijuvault.net
    service: http://npm:80
  - hostname: prowlarr.kaijuvault.net
    service: http://npm:80
  - hostname: radarr.kaijuvault.net
    service: http://npm:80
  - hostname: sonarr.kaijuvault.net
    service: http://npm:80
  - hostname: torrent.kaijuvault.net
    service: http://npm:80
  - hostname: bazarr.kaijuvault.net
    service: http://npm:80
  - hostname: request.kaijuvault.net
    service: http://npm:80
  - hostname: sonarr-anime.kaijuvault.net
    service: http://npm:80
  - hostname: homarr.kaijuvault.net
    service: http://npm:80
  - hostname: unraid.kaijuvault.net
    service: http://npm:80
  - hostname: join.kaijuvault.net
    service: http://npm:80
  - hostname: glance.kaijuvault.net
    service: http://npm:80
  - hostname: stats.kaijuvault.net
    service: http://npm:80
  - service: http_status:404
